In [1]:
import numpy as np
import tensorflow as tf
import keras
from tensorflow.keras import backend
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
from keras.utils import np_utils
import seaborn as sns
from tensorflow.keras.initializers import RandomNormal

Using TensorFlow backend.


In [2]:
train=pd.read_csv('mnist_train.csv')
test=pd.read_csv('mnist_test.csv')

In [3]:
X_train=train.iloc[:,1:].values

In [4]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [5]:
X_train.shape

(60000, 784)

In [6]:
Y_train=train.iloc[:,0].values

In [7]:
Y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [8]:
X_test=test.iloc[:,1:].values

In [9]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
Y_test=test.iloc[:,0].values

In [11]:
Y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [12]:
#convert Y test and train into OHE
Y_train=np_utils.to_categorical(Y_train,10)

In [13]:
Y_train[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [14]:
Y_test=np_utils.to_categorical(Y_test,10)

In [15]:
Y_test[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [16]:
#normalize the data 
X_train=X_train/255
X_test=X_test/255

In [17]:
X_train.shape

(60000, 784)

In [18]:
#Some parameters
input_dim=X_train.shape[1]
output_dim=10
nb_epoch=20
batch_size=128

In [20]:
from tensorflow.keras.initializers import RandomNormal
from keras.layers.normalization import BatchNormalization

In [21]:
#building a model with adding normalization
model_batch=tf.keras.Sequential()
model_batch.add(Dense(512, activation='sigmoid', input_shape=(input_dim,), kernel_initializer=RandomNormal(mean=0.0, stddev=0.039, seed=None)))
model_batch.add(BatchNormalization())

model_batch.add(Dense(128,activation='sigmoid',kernel_initializer=RandomNormal(mean=0,stddev=0.055,seed=None)))
model_batch.add(BatchNormalization())

model_batch.add(Dense(output_dim,activation='softmax'))
model_batch.summary()

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'